config/routes.rb
Rails.application.routes.draw do
  resources :players, except: [:destroy]
  resources :matches, except: [:destroy]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'players#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/elo_calculator.rb
class EloCalculator

  attr_reader :r1, :r2, :w1, :w2, :m
  K = 40

  def initialize(r1, r2, w1, w2, d=0)
    @r1, @r2, @w1, @w2 = r1.to_f, r2.to_f, w1, w2
    @m =  w1 + w2 + d
  end

  def delta
    K * (w1 - m * e1)
  end

  private

  def e1
    1.0 / ( 1 + 10 ** ((r2-r1)/400) )
  end

  # def e2
  #   1.0 - e1
  # end
end

app/models/match.rb
class Match < ActiveRecord::Base
  has_many :match_players
  has_many :players, through: :match_players, dependent: :destroy

  has_many :team_a_match_players, -> { where(team: 'A') }, class_name: 'MatchPlayer'
  has_many :team_b_match_players, -> { where(team: 'B') }, class_name: 'MatchPlayer'
  has_many :team_a_players, through: :team_a_match_players, class_name: 'Player', source: :player
  has_many :team_b_players, through: :team_b_match_players, class_name: 'Player', source: :player

  validate :validate_player_uniqueness
  validates :score_a, :score_b, :draws, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :team_a_players, presence: true
  validates :team_b_players, presence: true

  attr_accessor :team_a_player_names, :team_b_player_names
  before_validation :generate_player_ids

  scope :closed, -> { where(status: 'closed') }

  def close!
    transaction do
      store_points_on_join!
      recalculate_averages
      update_player_points!
      self.status = 'closed'
      save!
    end
  end

  def closed?
    status == 'closed'
  end

  def can_close?
    has_score? && !closed?
  end

  def has_score?
    score_a + score_b + draws > 0
  end

  private

  def validate_player_uniqueness
    unless player_ids.size == player_ids.uniq.size
      errors.add :players, 'should be unique across teams.'
    end
  end

  def recalculate_averages
    a_points = team_a_players.map(&:point)
    self.team_a_avg_point = a_points.sum.to_f / a_points.size
    b_points = team_b_players.map(&:point)
    self.team_b_avg_point = b_points.sum.to_f / b_points.size
  end

  def calculator
    @calculator ||= EloCalculator.new(team_a_avg_point, team_b_avg_point, score_a, score_b, draws)
  end

  def update_player_points!
    d = calculator.delta
    team_a_players.each do |player|
      player.update_attribute(:point, player.point + d)
    end
    team_b_players.each do |player|
      player.update_attribute(:point, player.point - d)
    end
  end

  def store_points_on_join!
    match_players.each do |mp|
      mp.update_attribute(:current_point, mp.player.point)
    end
  end

  def generate_player_ids
    %i(a b).each do |team_name|
      if (player_names = public_send(:"team_#{team_name}_player_names")).present?
        ids = player_names.split(' ').map do |player_name|
          Player.find_by_nick_or_name(player_name).try(:id)
        end
        public_send(:"team_#{team_name}_player_ids=", ids)
      end
    end
  end

end

app/models/match_player.rb
class MatchPlayer < ActiveRecord::Base
  belongs_to :player
  belongs_to :match
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :match_players
  has_many :matches, through: :match_players
  validates_presence_of :name

  attr_reader :win_count, :defeat_count

  def position
    Player.order('point DESC').pluck(:id).index { |player_id| player_id == self.id } + 1
  end

  def count_results!
    @win_count = 0
    @defeat_count = 0
    matches.closed.each do |match|
      if match.team_a_players.include? self
        if match.score_a > match.score_b
          @win_count += 1
        else
          @defeat_count += 1
        end
      else
        if match.score_a > match.score_b
          @defeat_count += 1
        else
          @win_count += 1
        end
      end
    end
  end

  def self.find_by_nick_or_name(nick_or_name)
    where("nickname = :nick_or_name OR name = :nick_or_name",
          nick_or_name: nick_or_name).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def new
    @match = Match.new
  end

  def create
    respond_to do |format|
      format.html do
        @match = Match.create(match_params)

        if @match.valid?
          @match.close!
          redirect_to root_path
        else
          render action: :new
        end
      end
      format.js do
        @match = Match.create(match_params)
        @match.close! if @match.valid?
        render json: @match
      end
    end
  end

  def match_params
    params.require(:match).permit(
      :score_a,
      :score_b,
      :draws,
      team_a_player_names: [],
      team_b_player_names: [],
      team_a_player_ids: [],
      team_b_player_ids: []
    )
  end
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  def index
    @players = Player.order('point DESC')
    @matches = Match.closed.order('created_at DESC').limit(10)
  end

  def show
    @player = Player.find(params[:id])
    @player.count_results!
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.order('point DESC')
    @matches = Match.closed.order('created_at DESC').limit(10)
  end

  def show
    @player = Player.find(params[:id])
    @player.count_results!
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.create(player_params)

    if @player.valid?
      redirect_to root_path
    else
      render action: :new
    end
  end

  def player_params
    params.require(:player).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper

  def players_for_select
    Player.all.map { |p| [p.name, p.id] }
  end
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/views/layouts/application.haml
!!!
%head
  %title League Lo
  = stylesheet_link_tag :application
  = javascript_include_tag :application
%body
  = render 'shared/header'
  .container
    = yield

app/views/matches/_form.html.haml
= form_for @match, html: { role: 'form' } do |f|
  - if @match.errors.size > 0
    .alert.alert-danger(role='alert')
      %button.close{"data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} &times;
        %span.sr-only Close
      = @match.errors.full_messages.join(', ')
  %fieldset
    %legend Create a Match
    .row.like-form-group
      .col-md-4.text-right
        .form-group.team{ class: @match.errors[:team_a_players].blank? ? '' : 'has-error' }
          = f.label :team_a_player_ids, 'Team A', class: 'control-label'
          = f.select :team_a_player_ids, players_for_select, { }, { class: 'form-control select2', multiple: true }
        .form-group{ class: @match.errors[:score_a].blank? ? '' : 'has-error' }
          = f.label :score_a, 'A Wins', class: 'control-label'
          = f.number_field :score_a, class: 'form-control'
      .col-md-4.text-center.foosball-middle
        .hidden-sm.hidden-xs= image_tag 'foosball_table_vertical.png'
        .hidden-md.hidden-lg= image_tag 'foosball_table_horizontal.png'
      .col-md-4.text-left
        .form-group.team{ class: @match.errors[:team_b_players].blank? ? '' : 'has-error' }
          = f.label :team_b_player_ids, 'Team B', class: 'control-label'
          = f.select :team_b_player_ids, players_for_select, { }, { class: 'form-control select2', multiple: true }
        .form-group{ class: @match.errors[:score_a].blank? ? '' : 'has-error' }
          = f.label :score_b, 'B Wins', class: 'control-label'
          = f.number_field :score_b, class: 'form-control'
    .row.hidden
      .col-md-2.col-md-offset-3.text-right
      .col-md-2.text-center
        .form-group{ class: @match.errors[:score_a].blank? ? '' : 'has-error' }
          = f.label :draws, 'Draws', class: 'control-label'
          = f.number_field :draws, class: 'form-control'
      .col-md-2
    .form-group.text-center
      %button.btn.btn-default Cancel
      %button.btn.btn-primary{:type => "submit"} Submit

app/views/matches/new.html.haml
.well
  = render 'form'

app/views/players/_form.html.haml
= form_for @player, html: { role: 'form' } do |f|
  - if @player.errors.size > 0
    .alert.alert-danger(role='alert')
      %button.close{"data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} &times;
        %span.sr-only Close
      = @player.errors.full_messages.join(', ')
  %fieldset
    %legend Create a Player
    .form-group{ class: @player.errors[:name].blank? ? '' : 'has-error' }
      = f.label :name, class: 'control-label'
      = f.text_field :name, class: 'form-control'
    .form-group.text-center
      %button.btn.btn-default Cancel
      %button.btn.btn-primary{:type => "submit"} Submit

app/views/players/index.html.haml
.container
  .row
    .col-md-6
      .pull-right
        = link_to 'New Player', new_player_path, class: 'btn btn-warning'
      %h1 Leaderboard
      %table.table.table-striped.table-hover.col-md-6
        %thead
          %th Position
          %th Name
          %th Points
        %tbody
          - @players.each_with_index do |player, index|
            %tr
              %td= index + 1
              %td= link_to player.name, player
              %td= player.point.to_i
    .col-md-6
      .pull-right
        = link_to 'New Match', new_match_path, class: 'btn btn-warning'
      %h1 Recent matches
      %table.table.table-striped.table-hover.col-md-6
        %thead
          %th Team A
          %th
          %th Team B
          %th Date
        %tbody
          - @matches.each do |match|
            %tr
              %td= match.team_a_players.map(&:name).join(', ')
              %td
                = match.score_a
                \- #{match.score_b}
              %td= match.team_b_players.map(&:name).join(', ')
              %td= match.created_at.to_formatted_s(:short)

app/views/players/new.html.haml
.row
  .col-md-4.col-md-offset-4
    .well
      = render 'form'

app/views/players/show.html.haml
%h1= @player.name

.row
  .col-md-3
    %table.table.table-striped.table-hover
      %tr
        %td Position
        %td= @player.position
      %tr
        %td Point
        %td= @player.point.to_i
      %tr
        %td Matches
        %td= @player.matches.closed.count
      %tr
        %td Wins
        %td= @player.win_count
      %tr
        %td Defeats
        %td= @player.defeat_count
  .col-md-9

app/views/shared/_header.html.haml
.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'League Lo', root_path, class: 'navbar-brand'
    .navbar-collapse.collapse.navbar-responsive-collapse
      %ul.nav.navbar-nav
        %li{class: params[:controller] == 'players' ? 'active' : ''}
          = link_to 'LeaderBoard', root_path
        %li{class: params[:controller] == 'matches' ? 'active' : ''}
          = link_to 'Create a Match', new_match_path